#!/bin/bash	

cyan='tput setaf 6'
yellow='tput setaf 3'
reset='tput sgr0'

# install yay

release=$(head /etc/os-release -n 1 | cut -d '"' -f 2)

case $release in 
	"Arch Linux"|"Antergos Linux"|"Manjaro Linux")
	
	if ! which yay > /dev/null; then
		./yay_install.sh

	fi
	yay $*
	;;
	
	"void")
		sudo xbps-install -S $*
	;;

	"Solus")
		if [ $1 = "-S" ]
		then
			sudo eopkg install $2 $3 $4 $5 $6 $7 $8 $9
		elif [ $1 = "-R" ]
		then
			sudo eopkg remove $2 $3 $4 $5 $6 $7 $8 $9
		else
			echo -e "\n$($cyan)// Invalid Argument!!"
			exit
		fi
	;;
	
	*)
		echo -e "\n$($cyan)// woops. you're probably not running an $($yellow)Arch $($cyan)based distro$($reset)\n"
	;;

esac
echo -e "\n$($cyan)// All done."
