#!/bin/bash	

cyan='tput setaf 6'
yellow='tput setaf 3'
red='tput setaf 1'
reset='tput sgr0'

# install yay

release=$(head /etc/os-release -n 1 | cut -d '"' -f 2)

case $release in 
	"Arch Linux"|"Antergos Linux"|"Manjaro Linux")
	
	if ! which yay > /dev/null; then
		./yay_install.sh

	fi
	yay $*
	;;
	
	"void")
		sudo xbps-install -S $*
	;;

	"Solus")
		if [ $1 = "-S" ]
		then
			sudo eopkg install $2 $3 $4 $5 $6 $7 $8 $9
		elif [ $1 = "-R" ]
		then
			sudo eopkg remove $2 $3 $4 $5 $6 $7 $8 $9
		else
			eopkg search $1 | sort | nl -s':  ' | tac > search.list
			cat search.list
			if ! [[ -s search.list ]]; then
				echo -e "$($red)\nNo package found in search$($reset)"
				exit
			fi
			echo -e "\n$($yellow)Packages to install (eg: 1 2 3)\n$($reset)"
			read -p ": " ch
			for choice in $ch; do
				line=`expr $(wc -l < search.list) - $choice + 1`
				head -n $line search.list | tail -1 | awk '{print $2}' >> install.list
			done
			sudo eopkg install $(echo $(cat install.list | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g"))
			rm install.list search.list
				
		fi
	;;
	
	*)
		echo -e "\n$($cyan)// woops. you're probably not running an $($yellow)Arch $($cyan)based distro$($reset)\n"
	;;

esac
echo -e "\n$($cyan)// All done."


#https://stackoverflow.com/questions/19296667/remove-ansi-color-codes-from-a-text-file-using-bash
